name: 📦 Package Request
description: Request a new package to be added to the tap
body:
  - type: input
    id: name
    attributes:
      label: Package Name

  - type: input
    id: url
    attributes:
      label: URL

  - type: textarea
    id: description
    attributes:
      label: Description
