package generator

import (
	"fmt"
	"io"
	"strings"
	"time"
)

// Version is the tap-tools version included in generated headers
const Version = "1.0.0"

// WriteHeader writes a standard header comment to generated package files
// This header serves multiple purposes:
// 1. Identifies the file was generated by tap-tools (not manually created)
// 2. Provides regeneration instructions
// 3. Shows when and by which tool the file was created
// 4. Confirms validation was performed during generation
func WriteHeader(w io.Writer, toolName, sourceURL string) error {
	header := fmt.Sprintf(`# Generated by %s v%s on %s
# Source: %s
# DO NOT EDIT - Regenerate with: ./%s generate %s
# Validation: Auto-validated with tap-validate --fix
`,
		toolName,
		Version,
		time.Now().Format("2006-01-02"),
		sourceURL,
		toolName,
		sourceURL,
	)

	_, err := io.WriteString(w, header+"\n")
	return err
}

// ValidateHeader checks if a file has the required "Generated by" header
// This is used by CI and pre-commit hooks to detect manual file creation
func ValidateHeader(content string) bool {
	// Look for the "Generated by tap-" marker
	// This is a simple check - the header package handles the generation
	if len(content) < 50 {
		return false
	}

	// Check for the header in first few lines
	firstLine := content
	if idx := strings.IndexByte(content, '\n'); idx > 0 {
		firstLine = content[:idx]
	}

	return len(firstLine) > 0 && firstLine[0] == '#' &&
		(strings.Contains(firstLine, "Generated by tap-cask") ||
			strings.Contains(firstLine, "Generated by tap-formula"))
}
