package generator

import (
	"bytes"
	"strings"
	"testing"
)

func TestWriteHeader(t *testing.T) {
	tests := []struct {
		name      string
		toolName  string
		sourceURL string
		wantErr   bool
	}{
		{
			name:      "valid tap-cask header",
			toolName:  "tap-cask",
			sourceURL: "https://github.com/user/repo",
			wantErr:   false,
		},
		{
			name:      "valid tap-formula header",
			toolName:  "tap-formula",
			sourceURL: "https://github.com/org/project",
			wantErr:   false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var buf bytes.Buffer
			err := WriteHeader(&buf, tt.toolName, tt.sourceURL)

			if (err != nil) != tt.wantErr {
				t.Errorf("WriteHeader() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if err != nil {
				return
			}

			output := buf.String()

			// Verify header contains required elements
			requiredStrings := []string{
				"Generated by " + tt.toolName,
				"Source: " + tt.sourceURL,
				"DO NOT EDIT",
				"Regenerate with:",
				"Validation: Auto-validated",
			}

			for _, req := range requiredStrings {
				if !strings.Contains(output, req) {
					t.Errorf("WriteHeader() missing required string: %q\nGot:\n%s", req, output)
				}
			}

			// Verify it starts with #
			if !strings.HasPrefix(output, "#") {
				t.Errorf("WriteHeader() should start with #, got: %s", output)
			}

			// Verify it ends with newline
			if !strings.HasSuffix(output, "\n") {
				t.Errorf("WriteHeader() should end with newline")
			}
		})
	}
}

func TestValidateHeader(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{
			name: "valid tap-cask header",
			content: `# Generated by tap-cask v1.0.0 on 2026-02-09
# Source: https://github.com/user/repo
# DO NOT EDIT - Regenerate with: ./tap-cask generate https://github.com/user/repo
# Validation: Auto-validated with tap-validate --fix

cask "app-linux" do
end`,
			want: true,
		},
		{
			name: "valid tap-formula header",
			content: `# Generated by tap-formula v1.0.0 on 2026-02-09
# Source: https://github.com/user/repo
# DO NOT EDIT - Regenerate with: ./tap-formula generate https://github.com/user/repo
# Validation: Auto-validated with tap-validate --fix

class App < Formula
end`,
			want: true,
		},
		{
			name: "missing header",
			content: `cask "app-linux" do
  version "1.0.0"
end`,
			want: false,
		},
		{
			name:    "empty content",
			content: "",
			want:    false,
		},
		{
			name: "wrong header format",
			content: `# This is a manual cask
cask "app-linux" do
end`,
			want: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := ValidateHeader(tt.content); got != tt.want {
				t.Errorf("ValidateHeader() = %v, want %v\nContent:\n%s", got, tt.want, tt.content)
			}
		})
	}
}
